import './style.css';
import * as XLSX from 'xlsx';

const KEY='compass-wa-v1';
const defaultState={contacts:[],campaign:{name:'',sender:'WhatsApp 1',intervalMin:30,intervalMax:60,mode:'balanced',variations:['','','','','']},queue:[],running:false,current:0,results:[]};
let state=load();
let timer=null;

function load(){try{return {...structuredClone(defaultState),...(JSON.parse(localStorage.getItem(KEY))||{})}}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function normPhone(v=''){return String(v).replace(/\D/g,'')}
function esc(v=''){return String(v).replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]))}
function pick(obj,names){for(const n of names){const k=Object.keys(obj).find(x=>x.trim().toLowerCase()===n);if(k!==undefined)return obj[k]}return ''}
function normalizeContact(row,i){return {id:i+1,name:pick(row,['nome','name']),phone:normPhone(pick(row,['telefone','celular','whatsapp','phone','numero','número'])),company:pick(row,['empresa','company']),tags:pick(row,['tags','tag','segmento']),selected:true,...row}}

const app=document.querySelector('#app');
app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand">Compass WhatsApp</div><nav class="nav">
<button data-view="dashboard" class="active">Dashboard</button><button data-view="contacts">Contatos</button><button data-view="campaign">Campanha</button><button data-view="dispatch">Disparo</button><button data-view="report">Relatório</button></nav></aside><main class="main"><div id="view"></div></main></div>`;

document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));
function navActive(v){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v))}

function show(v='dashboard'){navActive(v);({dashboard,contacts,campaign,dispatch,report}[v]||dashboard)()}
function header(title,sub=''){return `<div class="top"><div><h1>${title}</h1>${sub?`<div class="muted">${sub}</div>`:''}</div><span class="badge">Dados locais · sem banco</span></div>`}

function dashboard(){const valid=state.contacts.filter(c=>c.phone).length;const done=state.results.length;view.innerHTML=header('Dashboard','Operação local com Excel como arquivo de continuidade')+`<div class="grid">
<div class="card metric"><span>Contatos</span><strong>${state.contacts.length}</strong><small class="muted">${valid} com telefone válido</small></div>
<div class="card metric"><span>Selecionados</span><strong>${state.contacts.filter(c=>c.selected).length}</strong><small class="muted">para a próxima campanha</small></div>
<div class="card metric"><span>Processados</span><strong>${done}</strong><small class="muted">na sessão/campanha atual</small></div>
<div class="card metric"><span>Variações</span><strong>${state.campaign.variations.filter(Boolean).length}</strong><small class="muted">mensagens configuradas</small></div></div>
<div class="card section"><h3>Fluxo recomendado</h3><p>1. Importe a planilha. 2. Revise e selecione contatos. 3. Configure campanha e variações. 4. Monte a fila. 5. Execute/pausa a fila. 6. Exporte o relatório.</p></div>`}

function contacts(){view.innerHTML=header('Contatos','Importe .xlsx, .xls ou .csv; os dados permanecem neste navegador')+`<div class="card"><div class="row">
<div class="field"><label>Planilha</label><input id="file" type="file" accept=".xlsx,.xls,.csv"/></div><div class="field"><label>Pesquisar</label><input id="search" placeholder="Nome, telefone, empresa ou tag"/></div></div>
<div class="row" style="margin-top:12px"><button class="btn secondary" id="all">Selecionar todos</button><button class="btn secondary" id="none">Desmarcar todos</button><button class="btn danger" id="clear">Limpar contatos</button></div></div><div class="card section table-wrap" id="ctable"></div>`;
file.onchange=importExcel;search.oninput=renderContacts;all.onclick=()=>{state.contacts.forEach(c=>c.selected=true);save();renderContacts()};none.onclick=()=>{state.contacts.forEach(c=>c.selected=false);save();renderContacts()};clear.onclick=()=>{if(confirm('Remover todos os contatos deste navegador?')){state.contacts=[];save();renderContacts()}};renderContacts()}
function renderContacts(){const q=(document.querySelector('#search')?.value||'').toLowerCase();const rows=state.contacts.filter(c=>JSON.stringify(c).toLowerCase().includes(q));ctable.innerHTML=rows.length?`<table class="table"><thead><tr><th></th><th>Nome</th><th>Telefone</th><th>Empresa</th><th>Tags</th><th>Validação</th></tr></thead><tbody>${rows.map(c=>`<tr><td><input type="checkbox" data-id="${c.id}" ${c.selected?'checked':''}></td><td>${esc(c.name)}</td><td>${esc(c.phone)}</td><td>${esc(c.company)}</td><td>${esc(c.tags)}</td><td class="${c.phone.length>=10?'ok':'err'}">${c.phone.length>=10?'OK':'Revisar'}</td></tr>`).join('')}</tbody></table>`:`<div class="empty">Nenhum contato importado.</div>`;ctable.querySelectorAll('input[type=checkbox]').forEach(x=>x.onchange=()=>{const c=state.contacts.find(c=>c.id==x.dataset.id);c.selected=x.checked;save()})}
async function importExcel(e){const f=e.target.files[0];if(!f)return;const data=await f.arrayBuffer();const wb=XLSX.read(data,{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(ws,{defval:''});state.contacts=rows.map(normalizeContact).filter(c=>Object.values(c).some(Boolean));save();renderContacts()}

function campaign(){const c=state.campaign;view.innerHTML=header('Campanha','Configure o conteúdo antes de montar a fila')+`<div class="card"><div class="row"><div class="field"><label>Nome da campanha</label><input id="cname" value="${esc(c.name)}" placeholder="Ex.: Prospecção NR-1 Setembro"></div><div class="field"><label>WhatsApp remetente</label><input id="sender" value="${esc(c.sender)}" placeholder="Ex.: GEB Empresarial"></div></div><div class="row" style="margin-top:12px"><div class="field"><label>Intervalo mínimo (seg)</label><input id="imin" type="number" min="1" value="${c.intervalMin}"></div><div class="field"><label>Intervalo máximo (seg)</label><input id="imax" type="number" min="1" value="${c.intervalMax}"></div><div class="field"><label>Rodízio</label><select id="mode"><option value="balanced" ${c.mode==='balanced'?'selected':''}>Equilibrado</option><option value="sequential" ${c.mode==='sequential'?'selected':''}>Sequencial</option><option value="random" ${c.mode==='random'?'selected':''}>Aleatório</option></select></div></div></div><div class="card section"><h3>Variações de mensagem</h3><p class="muted">Use {{nome}}, {{empresa}} e {{telefone}} como variáveis.</p><div class="variations">${c.variations.map((m,i)=>`<div class="field"><label>Variação ${i+1}</label><textarea data-var="${i}" placeholder="Mensagem ${i+1}">${esc(m)}</textarea></div>`).join('')}</div><div style="margin-top:14px"><button id="saveCampaign" class="btn primary">Salvar campanha</button></div></div>`;
saveCampaign.onclick=()=>{state.campaign.name=cname.value.trim();state.campaign.sender=sender.value.trim();state.campaign.intervalMin=Math.max(1,+imin.value||1);state.campaign.intervalMax=Math.max(state.campaign.intervalMin,+imax.value||state.campaign.intervalMin);state.campaign.mode=mode.value;document.querySelectorAll('[data-var]').forEach(t=>state.campaign.variations[+t.dataset.var]=t.value);save();alert('Campanha salva neste navegador.')}}

function buildQueue(){const vars=state.campaign.variations.filter(x=>x.trim());if(!vars.length)return alert('Cadastre ao menos uma variação de mensagem.');const selected=state.contacts.filter(c=>c.selected&&c.phone.length>=10);if(!selected.length)return alert('Nenhum contato válido selecionado.');state.queue=selected.map((c,i)=>{let idx=0;if(state.campaign.mode==='random')idx=Math.floor(Math.random()*vars.length);else idx=i%vars.length;return {contactId:c.id,variation:idx,status:'pendente'}});state.current=0;state.results=[];state.running=false;save();dispatch()}
function dispatch(){const total=state.queue.length,done=state.results.length,pct=total?Math.round(done/total*100):0;view.innerHTML=header('Disparo','Fila local: enquanto o navegador estiver aberto')+`<div class="card"><div class="statusbar"><strong>${done}/${total}</strong><div class="progress"><span style="width:${pct}%"></span></div><span>${pct}%</span></div><div class="row" style="margin-top:16px"><button class="btn secondary" id="build">Montar/reiniciar fila</button><button class="btn primary" id="start" ${!total?'disabled':''}>${state.running?'Em execução':'Iniciar'}</button><button class="btn secondary" id="pause">Pausar</button><button class="btn danger" id="cancel">Cancelar fila</button></div></div><div class="card section"><h3>Campanha</h3><p><strong>${esc(state.campaign.name||'Sem nome')}</strong> · ${esc(state.campaign.sender)}</p><p class="muted">Intervalo: ${state.campaign.intervalMin}–${state.campaign.intervalMax}s · ${state.campaign.variations.filter(Boolean).length} variação(ões)</p></div><div class="card section table-wrap" id="qtable"></div>`;
build.onclick=buildQueue;start.onclick=startQueue;pause.onclick=pauseQueue;cancel.onclick=()=>{pauseQueue();state.queue=[];state.current=0;state.results=[];save();dispatch()};renderQueue()}
function renderQueue(){if(!qtable)return;const rows=state.queue.slice(0,200).map((q,i)=>{const c=state.contacts.find(x=>x.id===q.contactId)||{};return `<tr><td>${i+1}</td><td>${esc(c.name)}</td><td>${esc(c.phone)}</td><td>V${q.variation+1}</td><td>${esc(q.status)}</td></tr>`});qtable.innerHTML=rows.length?`<table class="table"><thead><tr><th>#</th><th>Nome</th><th>Telefone</th><th>Variação</th><th>Status</th></tr></thead><tbody>${rows.join('')}</tbody></table>`:`<div class="empty">Monte a fila para iniciar.</div>`}
function renderTemplate(t,c){return t.replace(/{{\s*nome\s*}}/gi,c.name||'').replace(/{{\s*empresa\s*}}/gi,c.company||'').replace(/{{\s*telefone\s*}}/gi,c.phone||'')}
function randomWait(){const a=state.campaign.intervalMin,b=state.campaign.intervalMax;return Math.floor(Math.random()*(b-a+1)+a)*1000}
function startQueue(){if(state.running)return;state.running=true;save();step()}
function pauseQueue(){state.running=false;if(timer)clearTimeout(timer);timer=null;save();if(document.querySelector('#view'))dispatch()}
function step(){if(!state.running)return;const idx=state.queue.findIndex(q=>q.status==='pendente');if(idx<0){state.running=false;save();dispatch();return}const q=state.queue[idx],c=state.contacts.find(x=>x.id===q.contactId),vars=state.campaign.variations.filter(Boolean),msg=renderTemplate(vars[q.variation%vars.length],c);
q.status='processado';state.results.push({campaign:state.campaign.name,sender:state.campaign.sender,name:c.name,phone:c.phone,company:c.company,tags:c.tags,variation:q.variation+1,message:msg,processedAt:new Date().toISOString(),status:'processado'});save();dispatch();if(state.running){timer=setTimeout(step,randomWait())}}

function report(){view.innerHTML=header('Relatório','Exporte o resultado e use o Excel como histórico')+`<div class="card"><div class="row"><button class="btn primary" id="exportResults">Exportar relatório .xlsx</button><button class="btn secondary" id="exportContacts">Exportar contatos atuais .xlsx</button><button class="btn danger" id="clearResults">Limpar resultado local</button></div></div><div class="card section table-wrap" id="rtable"></div>`;
exportResults.onclick=()=>exportXlsx(state.results,'relatorio-compass-whatsapp.xlsx','Relatório');exportContacts.onclick=()=>exportXlsx(state.contacts,'contatos-compass-whatsapp.xlsx','Contatos');clearResults.onclick=()=>{state.results=[];state.queue=[];state.current=0;save();report()};rtable.innerHTML=state.results.length?`<table class="table"><thead><tr><th>Nome</th><th>Telefone</th><th>Empresa</th><th>Variação</th><th>Status</th><th>Processado em</th></tr></thead><tbody>${state.results.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.phone)}</td><td>${esc(r.company)}</td><td>${r.variation}</td><td>${esc(r.status)}</td><td>${esc(r.processedAt)}</td></tr>`).join('')}</tbody></table>`:`<div class="empty">Ainda não há resultados nesta campanha.</div>`}
function exportXlsx(rows,name,sheet){if(!rows.length)return alert('Não há dados para exportar.');const ws=XLSX.utils.json_to_sheet(rows);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,sheet);XLSX.writeFile(wb,name)}

if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{})}
show('dashboard');
